[Bf16 & int8] [example & ckprofiler]
ROCmSoftwarePlatform/composable_kernel pull request #100
Opened 2022-02-27 16:52 UTC by rocking5566

2022-02-28 03:11 UTC, asroy commented
Please add unit test under ```test/```

2022-02-28 20:21 UTC, asroy commented on device_operation/src/device_conv2d_fwd_xdl_nhwc_kyxc_nhwk_bf16_instance.cpp
> +        DeviceConv2dFwdXdl_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<  bhalf_t,  bhalf_t,  bhalf_t,     F32, PassThrough, PassThrough, PassThrough, ConvFwdDefault,   256,   256,   128,     4,
Please fix all alignment issue in "instances.cpp"

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/22615726/156053065-76dc1b9f-9b52-460a-8bf9-b2f841e67c93.png">

2022-02-28 20:22 UTC, asroy requested changes
Please add test and fix alignment issue

2022-03-01 18:53 UTC, rocking5566 commented
> Please add test and fix alignment issue

Done

2022-03-02 18:10 UTC, asroy submitted a review, later dismissed

2022-03-04 07:30 UTC, asroy commented
Please fix merge conflict and CI failure

2022-03-04 21:56 UTC, asroy approved these changes

2022-03-04 21:56 UTC, merged