Gemm fp16 test
ROCmSoftwarePlatform/composable_kernel pull request #123
Opened 2022-03-11 07:52 UTC by rocking5566

Add gemm fp16 test

2022-03-20 12:19 UTC, ltqin commented on test/gemm/gemm_fp16.cpp
> +
Please add a check to check whether the queue is empty

2022-03-20 12:22 UTC, ltqin commented on test/gemm/gemm_fp16.cpp
> +}
it is better to write "return 0 "

2022-03-20 12:23 UTC, ltqin commented on test/gemm/gemm_fp32.cpp
>      std::cout << "TestGemm ..... " << (res ? "SUCCESS" : "FAILURE") << std::endl;
same with above

2022-03-20 12:29 UTC, ltqin commented on test/include/test_util.hpp
> +{
change _Float16 to ck::half_t?

2022-03-21 21:53 UTC, asroy commented
Please use ckProfiler to dp testing, instead of writting new test  code

You can reuse this function:
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/925ca9fcd61ce4cf6d6e7c6b76dad1500ad4f543/profiler/include/profile_gemm_impl.hpp#L72

2022-03-21 21:54 UTC, asroy requested changes
Please use ckProfiler to do testing, instead of writting new test  code

You can reuse this function:
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/925ca9fcd61ce4cf6d6e7c6b76dad1500ad4f543/profiler/include/profile_gemm_impl.hpp#L72

2022-03-23 10:08 UTC, closed without merging