Pass gemm_descs for grouped gemm via __constant__ buff
ROCmSoftwarePlatform/composable_kernel pull request #232
Opened 2022-05-11 21:49 UTC by zjing14

2022-05-13 01:01 UTC, rosenrodt commented
> > What will happen when two grouped gemm kernels run in parallel (given that each kernel is assigned its own hip stream)? Will they block each other's access to a globally defined `__constant__` buffer, or will they compete for the buffer and got the wrong data?
> 
> That is a good question. CK currently does not support that situation.

What prevents simply passing an array like `GemmDescKernelArg CK_CONSTANT_ADDRESS_SPACE*`? Our hardware doesn't have dedicated constant cache like NV does. But passing as constant address space allows the compiler to leverage read-only scalar cache. And by not using the global variable we can also avoid the thread-safety problem.

2022-05-16 13:33 UTC, zjing14 commented
@rosenrodt We tried CK_CONSTANT_ADDRESS_SPACE before, but cannot get it compiled, getting the error as below:

`error: cannot initialize a parameter of type '__attribute__((address_space(4)))`

2022-05-17 03:39 UTC, rosenrodt commented
My mistake. At one point CK was passing pointer by `const void  __attribute__((address_space(4))) *` and cast back to the intended type in the kernel. But the technique is no longer in use in current develop branch and I don't know why. Is it because compiler can already better recognize that it should use scalar loads? Could @asroy comment?

2022-05-20 04:29 UTC, asroy commented
> My mistake. At one point CK was passing pointer by `const void __attribute__((address_space(4))) *` and cast back to the intended type in the kernel. But the technique is no longer in use in current develop branch and I don't know why. Is it because compiler can already better recognize that it should use scalar loads? Could @asroy comment?

Previously, MIOpen require CK kernel to have C signature, so we cannot pass C++ object to kernel. so we use HipMemCpy to copy tensor descriptor from host to gpu memory, so kernel will read argument from gpu memory by a pointer. the "address_space(4)" trick is to hint compile to use s_load instead of v_load. That was a hack that is no longer needed, since now CK kernel use C++ signature.

Using __constant__ buffer is also a trick, so that each WG can access it like memory, based on run-time info like block-id, instead of static assert. Also we can use "hipMemcpyToSymbol" which should be faster than "hipMemCpy"

2022-05-20 04:34 UTC, asroy commented on include/ck/tensor_operation/gpu/device/device_grouped_gemm_xdl.hpp
> +__constant__ static char gemm_descs_const_[CK_GEMM_DESCS_CONSTANT_BUFF_SIZE];
Is this too big? Maybe it will take too long to finish data copy?

2022-05-20 04:35 UTC, asroy commented on include/ck/tensor_operation/gpu/device/device_grouped_gemm_xdl.hpp
> +#define CK_GEMM_DESCS_CONSTANT_BUFF_SIZE 1048576 // 1MB for 1000 gemm_descs
Better not use marco. You can hardcoded the gemm_descs_const_ sizes, and comment this is constant buffer

2022-05-20 04:49 UTC, asroy commented on include/ck/tensor_operation/gpu/device/device_grouped_gemm_xdl.hpp
> +#define CK_GEMM_DESCS_CONSTANT_BUFF_SIZE 1048576 // 1MB for 1000 gemm_descs
NVM, I see you are using CK_GEMM_DESCS_CONSTANT_BUFF_SIZE in multiple places

2022-05-20 04:49 UTC, asroy submitted a review, later dismissed

2022-05-20 05:00 UTC, asroy commented
Is constant memory safe for multiple kernels running at different stream? Is ```hipMemcpyToSymbol``` faster than ```hipMemcpy``` on AMD GPU?

If the answer is no, maybe we should just use regular ```hipMemcpy```, and use ```address_space(4)``` trick?

If so we need to introduce workspace

2022-05-20 05:37 UTC, zjing14 commented
I have no answer to the two questions currently. But I can confirm that the kernel with constant buffer is much faster than regular memory buffer.

2022-05-24 04:35 UTC, zjing14 commented
@asroy @rosenrodt Update the PR: using `const void __attribute__((address_space(4))) *` instead of global constant. Briefly tested the overhead of `HipMemAlloc` and `HipMemCpy` is roughly 0.05 ms. Using `HipMemCpySymbol` will take similar amount of time.

2022-05-24 06:21 UTC, rosenrodt commented
> @asroy @rosenrodt Update the PR: using `const void __attribute__((address_space(4))) *` instead of global constant. The overhead of `HipMemAlloc` and `HipMemCpy` is roughly 0.05 ms for 100 Gemms. Using `HipMemCpySymbol` will take similar amount of time.

Looks good. Is there any perf issue when compared to using \_\_constant\_\_ buffer?

2022-05-24 20:12 UTC, asroy requested changes

2022-05-24 20:12 UTC, asroy commented on include/ck/tensor_operation/gpu/device/device_grouped_gemm_xdl.hpp
> +            hipGetErrorString(hipMalloc(
We recently added ```GetWorkSpaceSize``` into ```BaseOperator ```

https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/40b59a63cc6308c01390e6ab07015a2f34a7b16a/include/ck/tensor_operation/gpu/device/device_base.hpp#L43

This hipMalloc can be moved out of this DeviceOperation

2022-05-25 16:48 UTC, zjing14 commented
@asroy Moved hipMemAlloc outside of DeviceOp. Please review the PR again.

2022-05-27 04:47 UTC, zjing14 commented
@shaojiewang @asroy @qianfengz Please take a look.

2022-05-27 07:59 UTC, shaojiewang submitted a review, later dismissed
LGTM for the ```GetWorkspaceSize``` and ```SetWorkSpacePointer``` part.

2022-05-27 23:43 UTC, asroy commented on include/ck/tensor_operation/gpu/device/device_base.hpp
> +    virtual void SetWorkSpacePointer(BaseArgument*, void*) const {}
Should we just add a ```p_workspace_``` member function to ```BaseArgument``` and implement this function as below?

```
void SetWorkSpacePointer(BaseArgument*, void* p_workspace) const
{ BaseArgument->p_workspace_ = p_workspace; }
```

I can do it in my PR.

2022-05-27 23:48 UTC, asroy commented on include/ck/tensor_operation/gpu/device/device_grouped_gemm_xdl.hpp
> +                    cast_pointer_to_constant_address_space(arg.gemm_descs_args_workspace_),
do we need casting pointer here? (on host)

2022-05-28 03:02 UTC, asroy commented
@zjing14  CI failed

2022-05-31 22:00 UTC, merged