B skip lds
ROCmSoftwarePlatform/composable_kernel pull request #289
Opened 2022-06-20 11:42 UTC by ltqin

1.b matrix skip lds
2.a matrix using 4 buffer

2022-06-20 17:46 UTC, asroy commented
Do we have performance study on this PR (performance number, thread trace, etc)? We would need that before we decide if we want to merge this PR

@ltqin @zjing14

2022-06-21 11:06 UTC, shaojiewang requested changes
1. Could you attach any perf data on MI100/MI200 using fp32/fp16?
2. If the layout is row-col-row, how to transpose data for the skipping lds side?

2022-06-21 11:06 UTC, shaojiewang commented on include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_skip_b_lds_v1.hpp
> +    static constexpr auto BaseMultK0 = 8;
Can ```BaseMultK0``` be a template? 
Also a typo, ```BaseMultiK0``` might be better.

2022-06-21 11:06 UTC, shaojiewang commented on include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdlops_skip_b_lds_v1.hpp
> +
Could you  please move these lines to a pipeline header?

2022-07-06 15:44 UTC, asroy commented
Please add license use the script here:

https://confluence.amd.com/display/MLSE/Development+Guide

2022-07-13 08:06 UTC, closed without merging