Make sure that GEMM sizes in K dimension are supported.
ROCmSoftwarePlatform/composable_kernel pull request #527
Opened 2022-12-02 15:41 UTC by illsilin

This is an additional check to catch the exception handled by asserts in develop mode when running a release build.
With this fix calls like "./bin/ckProfiler gemm 1 3 1 2 0 0 128 128 133 -1 -1 -1" will no longer produce wrong results and instead every kernel will issue an error message "does not support this problem".
I've also checked that other gemm sizes like 
"./bin/ckProfiler gemm 1 3 1 2 0 0 128 133 128 -1 -1 -1" 
or
"./bin/ckProfiler gemm 1 3 1 2 0 0 133 128 128 -1 -1 -1"
are also throwing the error. So no additional checks may be necessary.

2022-12-06 06:23 UTC, cloudhan commented
`DeviceBatchedGemm` seems also have the similar issue when one of m,n,k < 8. Does this PR also fix it?

2022-12-07 23:43 UTC, asroy requested changes

2022-12-08 00:43 UTC, illsilin commented on include/ck/tensor_operation/gpu/device/impl/device_batched_gemm_xdl.hpp
> +        if(arg.kraw_ % K1 != 0)
OK, so in terms of real variables, this should be something like this?

    static bool IsSupportedArgument(const Argument& arg)
    {
        bool valid = true;
        if(ALayout == 0)
        {
            valid &= (arg.kraw_ % ABlockTransferSrcScalarPerVector == 0)
        }
        else
        {
            valid &= (arg.mraw_ % ABlockTransferSrcScalarPerVector == 0)
        }

        if(BLayout == 0)
        {
            valid &= (arg.kraw_ % BBlockTransferSrcScalarPerVector == 0)
        }
        else
        {
            valid &= (arg.nraw_ % BBlockTransferSrcScalarPerVector == 0)
        }

        if(CLayout == 0)
        {
            valid &= (arg.mraw_ % CThreadTransferDstScalarPerVector == 0)
        }
        else
        {
            valid &= (arg.nraw_ % CThreadTransferDstScalarPerVector == 0)
        }

        if(!valid)
        {
            return false;
        }
        else
        {
            return GridwiseGemm::CheckValidity(arg.a_grid_desc_k0_m_k1_,
                                               arg.b_grid_desc_k0_n_k1_,
                                               arg.c_grid_desc_m_n_,
                                               arg.block_2_ctile_map_);
        }
    }

2022-12-08 00:55 UTC, cloudhan commented on include/ck/tensor_operation/gpu/device/impl/device_batched_gemm_xdl.hpp
> +        if(arg.kraw_ % K1 != 0)
`if constexpr (ALayout == 0)`?

2022-12-08 17:48 UTC, asroy approved these changes

2022-12-08 17:48 UTC, merged