Sphinx doc
ROCmSoftwarePlatform/composable_kernel pull request #581
Opened 2023-02-10 15:55 UTC by pmaybank

Set up infrastructure for generating HTML doc and start on a CK Primitives Guide.

2023-02-10 21:02 UTC, geyyer requested changes
Hi @pmaybank, thanks for adding this! Overall the PR looks like exactly what we need! Could you address the comments? Do you think we should add these docs to the new "docs" folder or add to the existing "doc" one? Which dependencies are we going to need for docs generation? Do you think we should add them to our docker images?

2023-02-13 12:33 UTC, pmaybank commented on .gitignore
> +docs/docBin/
Done

2023-02-13 12:33 UTC, pmaybank commented on docs/source/Disclaimer.rst
> +The information presented in this document is for informational purposes only and may contain technical inaccuracies, omissions, and typographical errors. The information contained herein is subject
Done

2023-02-13 12:33 UTC, pmaybank commented on docs/source/conf.py
> +"""Copyright (C) 2016-2023 Advanced Micro Devices, Inc. All rights reserved.
Done

2023-02-13 12:33 UTC, pmaybank commented on docs/source/conf.py
> +copyright = u'2016-2023, Advanced Micro Devices'
Done

2023-02-13 12:43 UTC, pmaybank commented
> Hi @pmaybank, thanks for adding this! Overall the PR looks like exactly what we need! ...

Thanks @geyyer for taking the time to look at this PR.  As a general comment before answering your questions, I based this work on what has been done for rocBLAS and rocFFT repositories.  I think following what has been done in those repositories is the simplest way forward, unless that are strong reasons for doing something different.  For example, this means using reStructuredText by default rather than Markdown.

Also, I was not aware of the doc directory when I created this PR as I had been working on a branch created before you created the doc directory.  Should have looked a bit more carefully as I may have done things a bit differently if I had known that doc was already there.

Re. your general questions,

> Do you think we should add these docs to the new "docs" folder or add to the existing "doc" one? 

rocBLAS and rocFFT both have "docs" directories.  I am inclined to follow what is done there.

> Which dependencies are we going to need for docs generation? 

Doxygen, Sphinx, and optionally CMake, I think.  Parts of the following blog may be helpful for getting dependencies set-up - https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/ .

> Do you think we should add them to our docker images?

I don't have much experience of generating / using docker images, so don't know.  Would be good to discuss.  I don't know if this is related, but I would like there to be some kind of pipeline for generating HTML that gets triggered whenever anyone pushes to remote so that latest doc can be easily accessed in a web browser.

Would be interested to discuss further in case I have missed anything.

2023-02-13 21:45 UTC, geyyer commented on docs/source/conf.py
> +source_suffix = '.rst'
I'm totally fine with just one "language / markup" for writing developer guides, let's stick to .rst.

2023-02-13 22:08 UTC, geyyer commented
@pmaybank, thanks for the editions and adding the existing docs!

> Do you think we should add these docs to the new "docs" folder or add to the existing "doc" one?
> 
> rocBLAS and rocFFT both have "docs" directories. I am inclined to follow what is done there.

Hmm, indeed rocBLAS and rocFFT have "docs", but MIOpen library has a "doc" dir https://github.com/ROCmSoftwarePlatform/MIOpen/tree/develop/doc. @zjing14, @asroy, what do you think is our plan to get a consistent naming within ROCm?

> Do you think we should add them to our docker images?
> 
> I don't have much experience of generating / using docker images, so don't know. Would be good to discuss. I don't know if this is related, but I would like there to be some kind of pipeline for generating HTML that gets triggered whenever anyone pushes to remote so that latest doc can be easily accessed in a web browser.

@illsilin, would it make any sense to include doc-related deps to our docker images? If we run a github action to publish the docs, is it simpler to get all the deps in a docker image or install them as a part of a GHA?

2023-02-15 19:40 UTC, zjing14 commented
@geyyer Please review and approve this PR.

2023-02-15 23:10 UTC, geyyer approved these changes
LGTM!

2023-02-15 23:17 UTC, merged