workaround 637
ROCmSoftwarePlatform/composable_kernel pull request #640
Opened 2023-03-15 09:55 UTC by ltqin

add workaround for issue 637
https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/637

2023-03-17 00:37 UTC, asroy requested changes

2023-03-17 00:37 UTC, asroy commented on include/ck/ck.hpp
> +#define CK_WORKAROUND_GITHUB_CK_ISSUE_637 1
CK_WORKAROUND_SWDEV_388832

2023-03-17 02:47 UTC, ltqin commented on include/ck/ck.hpp
> +#define CK_WORKAROUND_GITHUB_CK_ISSUE_637 1
done

2023-03-20 16:47 UTC, asroy approved these changes

2023-03-20 16:49 UTC, merged