Add small tile size for fp16/fp32 and NN layout
ROCmSoftwarePlatform/composable_kernel pull request #80
Opened 2022-02-08 00:14 UTC by zjing14

2022-02-09 15:46 UTC, asroy requested changes

2022-02-09 15:46 UTC, asroy commented on device_operation/include/device_gemm_xdl.hpp
> +#define USE_M_N_Padding 1
Please use a template argument to control this.


See ConvForwardSpecialization for reference
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/823657ed120144943b7db87c07fe3e647128db56/device_operation/include/device_conv2d_fwd_xdl_c_shuffle_nhwc_kyxc_nhwk.hpp#L122-L123

2022-02-10 06:00 UTC, asroy commented
Does this PR improve performance of small GEMM?

2022-02-10 06:06 UTC, zjing14 commented
> Does this PR improve performance of small GEMM?

Probably for extremely small Gemm. But this PR is mainly for supporting small M = 16, 32.

2022-02-10 07:53 UTC, asroy commented
I see some perf drop with this PR in 4K GEMM..

2022-02-11 04:29 UTC, zjing14 commented
> I see some perf drop with this PR in 4K GEMM..

Which configs? I will check if it is due to M/N padding.

2022-02-11 21:49 UTC, asroy approved these changes

2022-02-11 21:49 UTC, merged