Space filling curve
ROCmSoftwarePlatform/composable_kernel pull request #96
Opened 2022-02-22 20:49 UTC by j4yan

The space-filling-curve only, with S-shape traversal.

2022-02-23 04:56 UTC, asroy commented
unit test is not properly implemented

2022-02-23 04:57 UTC, asroy requested changes
Unit test is not properly implemented

2022-02-23 05:28 UTC, asroy commented on composable_kernel/include/utility/tensor_space_filling_curve.hpp
> +template <typename SliceLengths,
TensorLengths

2022-02-23 05:30 UTC, asroy commented on composable_kernel/include/utility/tensor_space_filling_curve.hpp
> +    template <int ii>
```int``` is not allowed in GPU code

use ```index_t``` only

2022-02-23 05:33 UTC, asroy commented
Please use clang-format-10 on the code

2022-02-23 05:36 UTC, asroy commented on composable_kernel/include/utility/tensor_space_filling_curve.hpp
> +    template <int ii>
Name it something meaningful instead of ```ii```

2022-02-23 05:37 UTC, asroy commented on composable_kernel/include/utility/tensor_space_filling_curve.hpp
> +        constexpr auto Id = Number<ii>{};
give it an meaningful name instead of ```Id```

2022-02-24 16:29 UTC, j4yan commented
@rosenrodt `DimAccessOrder` is the reordered dimensions, so `<2, 0, 1>` means we access dim-1, dim-0, dim-2 in order. It also confused me.

2022-02-24 22:34 UTC, asroy commented on composable_kernel/include/utility/tensor_space_filling_curve.hpp
> +        constexpr auto idx_next = GetIndex(Number<AccessIdx1d>{} + Number<1>{});
GetIndex(Number<AccessIdx1d-1>{});

2022-02-24 22:36 UTC, asroy commented on composable_kernel/include/utility/tensor_space_filling_curve.hpp
> +        constexpr auto idx_prev = GetIndex(Number<AccessIdx1d>{} - Number<1>{});
same as above

2022-02-24 22:45 UTC, j4yan commented on composable_kernel/include/utility/tensor_space_filling_curve.hpp
> +        constexpr auto idx_next = GetIndex(Number<AccessIdx1d>{} + Number<1>{});
resolved.

2022-02-24 22:45 UTC, j4yan commented on composable_kernel/include/utility/tensor_space_filling_curve.hpp
> +        constexpr auto idx_prev = GetIndex(Number<AccessIdx1d>{} - Number<1>{});
resolved.

2022-02-25 02:10 UTC, asroy approved these changes

2022-02-25 02:11 UTC, merged

2022-02-25 03:47 UTC, rosenrodt commented
> `DimAccessOrder` is the reordered dimensions, so `<2, 0, 1>` means we access dim-1, dim-0, dim-2 in order. It also confused me.

@j4yan Thanks for the clarification!